export default [
  {
    icon: "car",
    fullName: "Alabama",
    shortName: "AL",
    value: 1,
  },
  {
    icon: "car",
    fullName: "Alaska",
    shortName: "AK",
    value: 2,
  },
  {
    icon: "car",
    fullName: "Arizona",
    shortName: "AZ",
    value: 3,
  },
  {
    icon: "car",
    fullName: "Arkansas",
    shortName: "AR",
    value: 4,
  },
  {
    icon: "car",
    fullName: "California",
    shortName: "CA",
    value: 5,
  },
  {
    icon: "car",
    fullName: "Colorado",
    shortName: "CO",
    value: 6,
  },
  {
    icon: "car",
    fullName: "Connecticut",
    shortName: "CT",
    value: 7,
  },
  {
    icon: "car",
    fullName: "Delaware",
    shortName: "DE",
    value: 8,
  },
  {
    icon: "car",
    fullName: "Florida",
    shortName: "FL",
    value: 9,
  },
  {
    icon: "car",
    fullName: "Georgia",
    shortName: "GA",
    value: 10,
  },
  {
    icon: "car",
    fullName: "Hawaii",
    shortName: "HI",
    value: 11,
  },
  {
    icon: "car",
    fullName: "Idaho",
    shortName: "ID",
    value: 12,
  },
  {
    icon: "car",
    fullName: "Illinois",
    shortName: "IL",
    value: 13,
  },
  {
    icon: "car",
    fullName: "Indiana",
    shortName: "IN",
    value: 14,
  },
  {
    icon: "car",
    fullName: "Iowa",
    shortName: "IA",
    value: 15,
  },
  {
    icon: "car",
    fullName: "Kansas",
    shortName: "KS",
    value: 16,
  },
  {
    icon: "car",
    fullName: "Kentucky",
    shortName: "KY",
    value: 17,
  },
  {
    icon: "car",
    fullName: "Louisiana",
    shortName: "LA",
    value: 18,
  },
  {
    icon: "car",
    fullName: "Maine",
    shortName: "ME",
    value: 19,
  },
  {
    icon: "car",
    fullName: "Maryland",
    shortName: "MD",
    value: 20,
  },
  {
    icon: "car",
    fullName: "Massachusettes",
    shortName: "MA",
    value: 21,
  },
  {
    icon: "car",
    fullName: "Michigan",
    shortName: "MI",
    value: 22,
  },
  {
    icon: "car",
    fullName: "Minnesota",
    shortName: "MN",
    value: 23,
  },
  {
    icon: "car",
    fullName: "Mississippi",
    shortName: "MS",
    value: 24,
  },
  {
    icon: "car",
    fullName: "Missouri",
    shortName: "MO",
    value: 25,
  },
  {
    icon: "car",
    fullName: "Montana",
    shortName: "MT",
    value: 26,
  },
  {
    icon: "car",
    fullName: "Nebraska",
    shortName: "NE",
    value: 27,
  },
  {
    icon: "car",
    fullName: "Nevada",
    shortName: "NV",
    value: 28,
  },
  {
    icon: "car",
    fullName: "New Hampshire",
    shortName: "NH",
    value: 29,
  },
  {
    icon: "car",
    fullName: "New Jersey",
    shortName: "NJ",
    value: 30,
  },
  {
    icon: "car",
    fullName: "New Mexico",
    shortName: "NM",
    value: 31,
  },
  {
    icon: "car",
    fullName: "New York",
    shortName: "NY",
    value: 32,
  },
  {
    icon: "car",
    fullName: "North Carolina",
    shortName: "NC",
    value: 33,
  },
  {
    icon: "car",
    fullName: "North Dakota",
    shortName: "ND",
    value: 34,
  },
  {
    icon: "car",
    fullName: "Ohio",
    shortName: "OH",
    value: 35,
  },
  {
    icon: "car",
    fullName: "Oklahoma",
    shortName: "OK",
    value: 36,
  },
  {
    icon: "car",
    fullName: "Oregon",
    shortName: "OR",
    value: 37,
  },
  {
    icon: "car",
    fullName: "Pennsylvania",
    shortName: "PA",
    value: 38,
  },
  {
    icon: "car",
    fullName: "Rhode Island",
    shortName: "RI",
    value: 39,
  },
  {
    icon: "car",
    fullName: "South Carolina",
    shortName: "SC",
    value: 40,
  },
  {
    icon: "car",
    fullName: "South Dakota",
    shortName: "SD",
    value: 41,
  },
  {
    icon: "car",
    fullName: "Tennessee",
    shortName: "TN",
    value: 42,
  },
  {
    icon: "TX-Solid",
    fullName: "Texas",
    shortName: "TX",
    value: 43,
  },
  {
    icon: "TX-Solid",
    fullName: "Utah",
    shortName: "UT",
    value: 44,
  },
  {
    icon: "TX-Solid",
    fullName: "Vermont",
    shortName: "VT",
    value: 45,
  },
  {
    icon: "TX-Solid",
    fullName: "Virgina",
    shortName: "VA",
    value: 46,
  },
  {
    icon: "TX-Solid",
    fullName: "Washington",
    shortName: "WA",
    value: 47,
  },
  {
    icon: "TX-Solid",
    fullName: "West Virginia",
    shortName: "WV",
    value: 48,
  },
  {
    icon: "TX-Solid",
    fullName: "Wisconsin",
    shortName: "WI",
    value: 49,
  },
  {
    icon: "TX-Solid",
    fullName: "Wyoming",
    shortName: "WY",
    value: 50,
  }
]